import {
  User,
  Account,
  AccountType,
  AuditLogs,
  Bill,
  BillPayment,
  Budget,
  BudgetCategory,
  Category,
  Currency,
  Debt,
  DebtPayment,
  ExchangeRate,
  Goal,
  GoalContribution,
  Institution,
  InverstmentTrasaction,
  Investment,
  InvestmentType,
  Merchants,
  Notification,
  Profile,
  Receipt,
  RecurringTransactions,
  SecurityPrices,
  Subcategory,
  Tag,
  TaxCategory,
  TaxFiling,
  Transfer,
  UserPreferences,
} from "@/entities/index.ts";

export const db = {
  account: Account,
  accountType: AccountType,
  auditLogs: AuditLogs,
  bill: Bill,
  billPayment: BillPayment,
  budget: Budget,
  budgetCategory: BudgetCategory,
  category: Category,
  currency: Currency,
  debt: Debt,
  debtPayment: DebtPayment,
  exchangeRate: ExchangeRate,
  goal: Goal,
  goalContribution: GoalContribution,
  institution: Institution,
  inverstmentTrasaction: InverstmentTrasaction,
  investment: Investment,
  investmentType: InvestmentType,
  merchants: Merchants,
  notification: Notification,
  profile: Profile,
  receipt: Receipt,
  recurringTransactions: RecurringTransactions,
  securityPrices: SecurityPrices,
  subcategory: Subcategory,
  tag: Tag,
  taxCategory: TaxCategory,
  taxFiling: TaxFiling,
  transfer: Transfer,
  userPreferences: UserPreferences,
  user: User,
};
